name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install